name: job deploy server
 
on:
  push:
    branches:
      - 'deploy-server'

jobs:
  build_marketplace:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./honey-project
          file: ./honey-project/Dockerfile
          push: true
          tags: huynqph26782/udpm-portal-honney-api:0.0.1
  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: huynqph26782/udpm-portal-honney:0.0.1
      - 
       name: executing remote ssh commands using password
       uses: appleboy/ssh-action@v1.0.0
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         port: ${{ secrets.PORT }}
         script: |
            cd deploy-compose
            docker pull huynqph26782/udpm-portal-honney:0.0.1
            docker pull huynqph26782/udpm-portal-honney-api:0.0.1
            docker-compose up -d --build web_honey
            docker-compose up -d --build api_honey
            docker restart nginx-proxy
            docker image prune
    
        
  notifi_slack_bot:
    runs-on: ubuntu-latest
    needs: ['build_marketplace']
    steps:
      - name: Slack Notification Ci/Cd started
        uses: 8398a7/action-slack@v3.15.1
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: "Code mới hiện đã được deploy lên server, bạn có thể truy cập vào đường link https://honey.udpm-hn.com/ để trải nghiệm ứng dụng. Xin cảm ơn !!! 😒😒😒"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
